"""add processed_items table

Revision ID: 0ecb9c4795ca
Revises: 7fefd2fe33c8
Create Date: 2026-05-15 16:50:46.503274

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ecb9c4795ca"
down_revision: str | Sequence[str] | None = "7fefd2fe33c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("raw_item_id", sa.Integer(), nullable=False),
        sa.Column("normalized_title", sa.String(length=1000), nullable=False),
        sa.Column("canonical_url", sa.String(length=2048), nullable=False),
        sa.Column("content_track", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column("importance_score", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("keywords", sa.String(length=500), nullable=True),
        sa.Column("duplicate_group_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_track IN ('expert_news', 'practical_insight', 'both')",
            name="ck_processed_items_content_track",
        ),
        sa.ForeignKeyConstraint(["raw_item_id"], ["raw_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("raw_item_id", name="uq_processed_items_raw_item_id"),
    )
    with op.batch_alter_table("processed_items", schema=None) as batch_op:
        batch_op.create_index("ix_processed_items_canonical_url", ["canonical_url"], unique=False)
        batch_op.create_index(
            "ix_processed_items_duplicate_group_id", ["duplicate_group_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_processed_items_raw_item_id"), ["raw_item_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("processed_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_processed_items_raw_item_id"))
        batch_op.drop_index("ix_processed_items_duplicate_group_id")
        batch_op.drop_index("ix_processed_items_canonical_url")

    op.drop_table("processed_items")
    # ### end Alembic commands ###
