"""add newsletter_issues table

Revision ID: 774fdde3e389
Revises: 0ecb9c4795ca
Create Date: 2026-05-18 21:54:38.546696

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "774fdde3e389"
down_revision: str | Sequence[str] | None = "0ecb9c4795ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newsletter_issues",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("expert_section_md", sa.Text(), nullable=True),
        sa.Column("practical_section_md", sa.Text(), nullable=True),
        sa.Column("markdown_body", sa.Text(), nullable=True),
        sa.Column("html_body", sa.Text(), nullable=True),
        sa.Column("candidate_ids_json", sa.Text(), nullable=True),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('drafted', 'review_required', 'approved', 'sent', 'rejected')",
            name="ck_newsletter_issues_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("newsletter_issues", schema=None) as batch_op:
        batch_op.create_index("ix_newsletter_issues_issue_date", ["issue_date"], unique=False)
        batch_op.create_index("ix_newsletter_issues_status", ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("newsletter_issues", schema=None) as batch_op:
        batch_op.drop_index("ix_newsletter_issues_status")
        batch_op.drop_index("ix_newsletter_issues_issue_date")

    op.drop_table("newsletter_issues")
    # ### end Alembic commands ###
