"""add run_logs table

Revision ID: 7807e2a15a63
Revises: 774fdde3e389
Create Date: 2026-05-19 10:48:39.043850

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7807e2a15a63'
down_revision: str | Sequence[str] | None = '774fdde3e389'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('step', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('llm_tokens_in', sa.Integer(), nullable=False),
    sa.Column('llm_tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'success', 'failure')", name='ck_run_logs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_logs', schema=None) as batch_op:
        batch_op.create_index('ix_run_logs_started_at', ['started_at'], unique=False)
        batch_op.create_index('ix_run_logs_step', ['step'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_run_logs_step')
        batch_op.drop_index('ix_run_logs_started_at')

    op.drop_table('run_logs')
    # ### end Alembic commands ###
