"""add embedding columns to processed_items

Revision ID: 9638e8b6379e
Revises: 7807e2a15a63
Create Date: 2026-05-19 11:25:46.744961

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9638e8b6379e"
down_revision: str | Sequence[str] | None = "7807e2a15a63"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("processed_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("embedding", sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column("embedding_model", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("processed_items", schema=None) as batch_op:
        batch_op.drop_column("embedding_model")
        batch_op.drop_column("embedding")

    # ### end Alembic commands ###
