"""add sources table

Revision ID: a57208570cf9
Revises:
Create Date: 2026-05-15 15:37:37.989572

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a57208570cf9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("content_track", sa.String(length=32), nullable=False),
        sa.Column("endpoint", sa.String(length=1024), nullable=False),
        sa.Column("query", sa.String(length=500), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("region", sa.String(length=16), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("audience_level", sa.String(length=16), nullable=True),
        sa.Column("priority", sa.String(length=8), nullable=False),
        sa.Column("trust_level", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("fetch_interval", sa.String(length=16), nullable=False),
        sa.Column("auth_required", sa.Boolean(), nullable=False),
        sa.Column("rate_limit_note", sa.String(length=500), nullable=True),
        sa.Column("owner", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_track IN ('expert_news', 'practical_insight', 'both')",
            name="ck_sources_content_track",
        ),
        sa.CheckConstraint(
            "fetch_interval IN ('hourly', 'daily', 'weekly')", name="ck_sources_fetch_interval"
        ),
        sa.CheckConstraint("priority IN ('high', 'medium', 'low')", name="ck_sources_priority"),
        sa.CheckConstraint(
            "trust_level IN ('official', 'media', 'community')", name="ck_sources_trust_level"
        ),
        sa.CheckConstraint(
            "type IN ('NAVER_API', 'RSS', 'YOUTUBE_RSS', 'API', 'MANUAL')", name="ck_sources_type"
        ),
        sa.PrimaryKeyConstraint("source_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sources")
    # ### end Alembic commands ###
