"""add raw_items table

Revision ID: c516264ee115
Revises: a57208570cf9
Create Date: 2026-05-15 15:55:53.510193

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c516264ee115"
down_revision: str | Sequence[str] | None = "a57208570cf9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("raw_summary", sa.Text(), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["sources.source_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "url", name="uq_raw_items_source_url"),
    )
    with op.batch_alter_table("raw_items", schema=None) as batch_op:
        batch_op.create_index("ix_raw_items_collected_at", ["collected_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_items_source_id"), ["source_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raw_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_items_source_id"))
        batch_op.drop_index("ix_raw_items_collected_at")

    op.drop_table("raw_items")
    # ### end Alembic commands ###
