"""add notion archive columns to newsletter_issues

Revision ID: d6a907364141
Revises: d53f7d9672d0
Create Date: 2026-05-19 18:49:09.038727

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6a907364141"
down_revision: str | Sequence[str] | None = "d53f7d9672d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("newsletter_issues", schema=None) as batch_op:
        batch_op.add_column(sa.Column("notion_page_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("newsletter_issues", schema=None) as batch_op:
        batch_op.drop_column("archived_at")
        batch_op.drop_column("notion_page_id")

    # ### end Alembic commands ###
