"""add slack_sent_at to newsletter_issues

Revision ID: f5662d6e7ec4
Revises: d6a907364141
Create Date: 2026-05-20 17:27:07.502916

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5662d6e7ec4"
down_revision: str | Sequence[str] | None = "d6a907364141"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("newsletter_issues", schema=None) as batch_op:
        batch_op.add_column(sa.Column("slack_sent_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("newsletter_issues", schema=None) as batch_op:
        batch_op.drop_column("slack_sent_at")

    # ### end Alembic commands ###
